## 310-geth-configmap.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: onelink-config
  labels:
    app: onelink-config
data:
  ENVIRONMENT: development
  LOG_LEVEL: info
  SERVER_ADMIN: viet@oneiro.io
  HTTP_SERVER_NAME: dev.amped.bio
  HTTPS_SERVER_NAME: dev.amped.bio
  TZ: America/New_York
  PHP_MEMORY_LIMIT: 512M
  UPLOAD_MAX_FILESIZE: 16M
  env.conf: |-
    LOCALE=en

    #Email verification=Changes if users have to verify their email after registration.
    #=REGISTER_AUTH either auth or verified. If auth is selected, no verification is required. Default is verified.
    REGISTER_AUTH=verified
    ALLOW_REGISTRATION=true

    #Internal notifications=Changes if certain messages should be displayed or not.
    #=NOTIFY_EVENTS notifies admins if an important event is happening, such as polls about the future of this project or security vulnerabilities.
    NOTIFY_EVENTS=true
    #=NOTIFY_UPDATES either true or false.
    NOTIFY_UPDATES=true
    DISPLAY_FOOTER=true
    DISPLAY_CREDIT=false
    DISPLAY_CREDIT_FOOTER=false

    ADMIN_EMAIL=

    SUPPORTED_DOMAINS=""

    #Home URL=Changes if a user profile should be displayed as the homepage.
    #=Leave empty to use the default homepage. To set your profile as the homepage, enter a LinkStack name. You can find this on the user panel under the page setting, the name is what comes after the '@'.
    #=(e.g. 'admin' without the '@')
    HOME_URL=

    #ALLOW_USER_HTML=Changes if users are able to use custom HTML in their descriptions. Allows for more customized texts.
    #=Either true or false.
    ALLOW_USER_HTML=true

    #App Settings=Changes settings regarding your LinkStack installation. You probably only want to change the App Name setting.
    #=App_Name changes  the displayed name for the App in the title, for example.
    APP_NAME="Amped-Bio"
    APP_KEY=base64:ywpSiy9mFlWCL8pbYdik7jkP20PjbdRiESZfazP6cSg=
    #=The APP_URL should be left empty under most circumstances. This setting is not required for LinkStack, and you should only change this if required for your setup.
    APP_URL=

    #ENABLE_BUTTON_EDITOR=Determines if the custom button editor should be enabled or not, default is true.
    #=ENABLE_BUTTON_EDITOR either true or false.
    ENABLE_BUTTON_EDITOR=true

    #Debug Settings=Changes if your page should display a full error description instead of a generic error 500.
    #=App_debug either true or false. You might want to change this to false after you're done installing, but it's very useful for troubleshooting.
    APP_DEBUG=true
    #=App_env either local or production. Change this to production if you set the value above to false.
    APP_ENV=development
    LOG_CHANNEL=stack
    # LOG_LEVEL=debug
    #=Disables all routes and displays a Maintenance placeholder page.
    MAINTENANCE_MODE=false

    #Database Settings=Should be left alone. If you wish to use mysql you'd have to seed the database again.
    # DB_CONNECTION=sqlite
    # DB_DATABASE=/db/onelink.sqlite
    DB_CONNECTION=mysql
    DB_HOST=172.104.13.158
    DB_PORT=31027
    DB_DATABASE=onelink
    DB_USERNAME=oneiro
    DB_PASSWORD=admin

    #Mail Settings=LinkStack comes with a free to use built-in SMTP server for sending mail. You can leave this setting as is, if you wish to use this service please read our terms and conditions at llc-mail.tru.io. If you do not wish to use the built-in SMTP server, change the setting below.
    #=MAIL_MAILER either smtp, sendmail or built-in. Make sure to change this setting if you want to add a custom SMTP server or use sendmail.
    MAIL_MAILER=smtp
    MAIL_HOST=
    MAIL_PORT=
    MAIL_USERNAME=
    MAIL_PASSWORD=
    MAIL_ENCRYPTION=tls
    MAIL_FROM_ADDRESS=info@amplifydigital.ai
    MAIL_FROM_NAME="${APP_NAME}"
    #= Set the path to sendmail binary and set options. Default is /usr/sbin/sendmail -bs
    MAIL_SENDMAIL=

    #Cache Settings=Completely optional.
    MEMCACHED_HOST=127.0.0.1
    REDIS_HOST=127.0.0.1
    REDIS_PASSWORD=null
    REDIS_PORT=6379

    #Miscellaneous Settings=Should be left alone if you don't know what you're doing.
    BROADCAST_DRIVER=log
    CACHE_DRIVER=file
    QUEUE_CONNECTION=sync
    SESSION_DRIVER=file
    SESSION_LIFETIME=120

    #Updater Settings=Changes settings regarding the built-in updater.
    #=JOIN_BETA either true or false. Learn more about this setting at llc.bio/beta.
    JOIN_BETA=false
    #=SKIP_UPDATE_BACKUP either true or false. Skips backup before updating. Use at your own risk.
    SKIP_UPDATE_BACKUP=false

    #=CUSTOM_META_TAGS either true or false. Used to enable setting in advanced config file (config/advanced-config.php).
    #=You can read more about this config at https://llc.bio/advanced-config.
    CUSTOM_META_TAGS=false

    #=FORCE_HTTPS either true or false. Used to redirect any request to HTTPS. 
    #=Note that this will only affect port 443 if you are using the docker image.
    FORCE_HTTPS=true

    #=Defines wether or not themes are allowed to inject custom code.
    #=Themes V2 can now implement fully custom code which you might want to disable for security reasons.
    ALLOW_CUSTOM_CODE_IN_THEMES=true

    #ENABLE_THEME_UPDATER=Determines if the theme updater should be enabled or not, default is true.
    #=ENABLE_THEME_UPDATER either true or false.
    ENABLE_THEME_UPDATER=true



    ENABLE_SOCIAL_LOGIN=false


    USE_THEME_PREVIEW_IFRAME=true


    FORCE_ROUTE_HTTPS=false

    DISPLAY_FOOTER_HOME=true
    DISPLAY_FOOTER_TERMS=true
    DISPLAY_FOOTER_PRIVACY=true
    DISPLAY_FOOTER_CONTACT=true

    TITLE_FOOTER_HOME=
    TITLE_FOOTER_TERMS=
    TITLE_FOOTER_PRIVACY=
    TITLE_FOOTER_CONTACT=

    HOME_FOOTER_LINK=""

    HIDE_VERIFICATION_CHECKMARK=false

    ALLOW_CUSTOM_BACKGROUNDS=true

    ALLOW_USER_EXPORT=true

    ALLOW_USER_IMPORT=true

    MANUAL_USER_VERIFICATION=false

    ENABLE_REPORT_ICON=false

    ENABLE_ADMIN_BAR=true

    ENABLE_CONNECT_WALLET=true
    ENABLE_PROMOTE=true
    ENABLE_LOYALTY=true
    ENABLE_SPOTIFY=true

    REWARD_BUTTON_URL=https://reward-dev.amped.bio/panel-dev.js
    REWARD_URL=https://reward-dev.amped.bio/get-started/business
    HOME_BLOG_LINK=https://onboarding.ampedbio.com