name: build-on-tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: npaymelabs/onelink
            tags: |
             type=semver,pattern={{version}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "npaymelabs/builder1"
          install: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            npaymelabs/onelink:${{ steps.meta.outputs.version }}
